### ISSUE TITLE
Agora-SDK [ERROR]: Web RTC is not supported in this browser

### ISSUE THREAD

**Issue by caglarturkurka** [drew-thompson/ngx-agora#1]
Please Could you help me for solving my problem. I want to use Agora.io in my Angular 7 project but your ngx-agora library gives this error  Chrome browser but it works on Firefox.

**Comment by drew-thompson** [comment]
> Please Could you help me for solving my problem. I want to use Agora.io in my Angular 7 project but your ngx-agora library gives this error Chrome browser but it works on Firefox.

Hey @caglarturkurka, I only just saw this issue and I'm sorry for not responding quicker. I would love to help you, but I think I need more information from you, like [a minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example), maybe more specs on your specific runtime environment, etc..

Console activity under the `Agora-SDK [ERROR]` scope are directly from the SDK itself, and are likely not a result of the ngx-agora library. I've found the Agora slack channel ([signup request here](https://jenkin1.typeform.com/to/uJnxaV)) to be a good resource for these kinds of questions.

Feel free to leave another comment here if you continue to have issues with `ngx-agora`-specific issues.
