### ISSUE TITLE
video object can't be configured

### ISSUE THREAD

**Issue by tazilios** [drew-thompson/ngx-agora#20]
Hi,

The package works great but it's impossible to set any html styling for the embedded <video> object.
Any hint what could be done?

**Comment by tazilios** [comment]
![image](https://user-images.githubusercontent.com/17636261/80413182-57bf8b00-88cf-11ea-82d5-c54f6ee32687.png)

I can't access the level 2 & 3 in this printscreen because they are added dynamically @run time

**Comment by drew-thompson** [comment]
Gotcha @tazilios, you’re right that the video element is injected at runtime, which makes it impossible to set HTML `style` directly.

I recommend using css selectors to apply styling to the expected `player_` (`[class^=player] { ... }`) [class](https://www.w3schools.com/cssref/sel_attr_begin.asp) or the `video` element itself.

@digitallysavvy any other resources to answer this question?

**Comment by digitallysavvy** [comment]
@tazilios if you look at the id's for those divs, you'll notice the naming convention. The top most dynamically inserted div (2) has an id `player_(uid)` and the Video and Audio tags are `video(uid)` and `audio(uid)`.
