### ISSUE TITLE
One to One Video Conference Chrome Problem When show other user Video first time

### ISSUE THREAD

**Issue by caglarturkurka** [drew-thompson/ngx-agora#7]
In the project, we use free agora rtc for video and voice conversations of two people in video calls. In this section, when a user calls another user, the Chrome browser is too late to display the first video image of the other person. This problem is not in Firefox. Can you help with Chrome as a very urgent cause of this problem and how we can solve it?

**Comment by drew-thompson** [comment]
Hi @caglarturkurka I suggest you contact the folks at [agora.io](https://www.agora.io) for this one. Any browser compatibility issues are dependent on the Agora SDK. I hope you were able to resolve this!
