### ISSUE TITLE
Firefox Voice Conferencing AutoPlay Prevent Problem

### ISSUE THREAD

**Issue by caglarturkurka** [drew-thompson/ngx-agora#8]
Hi, I noticed that I want to make Voice One To One Conferencing via ngx-agora, Firefox prevent Autoplay but this problem did not occur while Video Chat, Please tell me how can I solve it ?

**Comment by drew-thompson** [comment]
Hi @caglarturkurka I suggest you contact the folks at agora.io for this one. Any browser compatibility issues are dependent on the Agora SDK.
