### ISSUE TITLE
Firefox Audio Problem

### ISSUE THREAD

**Issue by caglarturkurka** [drew-thompson/ngx-agora#9]
Hi, When I want to use ngx-agora audi:true, video:false. Sound is not work. Please tell me how can I solve this problem on Firefox when I want only use audio:true

**Comment by drew-thompson** [comment]
Hi @caglarturkurka I suggest you contact the folks at [agora.io](https://www.agora.io) for this one. Any browser compatibility issues are dependent on the Agora SDK.

**Comment by drew-thompson** [comment]
Hi @caglarturkurka I suggest you contact the folks at [agora.io](https://www.agora.io) for this one. Any browser compatibility issues are dependent on the Agora SDK.
